# Generated by Django 5.1.2 on 2026-03-22 22:19

from django.db import migrations, models


def generate_unique_codigo(apps, schema_editor):
    MateriaPrima = apps.get_model('inventario', 'MateriaPrima')
    # Build a set of existing codes to avoid collisions
    existing = set(MateriaPrima.objects.values_list('codigo', flat=True))
    # Assign codes based on the existing id to ensure uniqueness for rows missing codigo
    for obj in MateriaPrima.objects.all().order_by('id'):
        codigo = getattr(obj, 'codigo', None)
        if not codigo:
            candidate = f"MP-{obj.id:04d}"
            # if candidate already used (unlikely), find next free number
            i = obj.id
            while candidate in existing:
                i += 1
                candidate = f"MP-{i:04d}"
            obj.codigo = candidate
            obj.save(update_fields=['codigo'])
            existing.add(candidate)


def noop(apps, schema_editor):
    # Reverse operation is a no-op (codes can remain)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_movimientoinventario_inventario_materiaprima_and_more'),
    ]

    operations = [
        # Add 'codigo' without unique constraint first to avoid UNIQUE collisions
        migrations.AddField(
            model_name='materiaprima',
            name='codigo',
            field=models.CharField(null=True, editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        # Populate unique codigo values for existing rows
        migrations.RunPython(generate_unique_codigo, reverse_code=noop),
        # Now enforce uniqueness
        migrations.AlterField(
            model_name='materiaprima',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True, null=False),
        ),
    ]
