# Generated by Django 6.0.2 on 2026-04-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_materiaprima_codigo_materiaprima_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('g', 'Gramo (g)'), ('l', 'Litro (l)'), ('ml', 'Mililitro (ml)'), ('m', 'Metro (m)'), ('cm', 'Centímetro (cm)'), ('pz', 'Pieza (pz)'), ('caja', 'Caja'), ('bulto', 'Bulto'), ('otro', 'Otro')], default='pz', max_length=20),
        ),
    ]
