# Generated by Django 6.0.6 on 2026-06-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_materiaprima_unidad_medida'),
        ('proveedores', '0003_proveedor_deleted_proveedor_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientomateriaprima',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='movimientomateriaprima',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor'),
        ),
        migrations.AlterField(
            model_name='movimientomateriaprima',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.materiaprima'),
        ),
    ]
