# Generated by Django 6.0.2 on 2026-03-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_telefono',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_venta',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
