# Generated by Copilot to add logistic workflow fields to Venta

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
