# Generated by Django 6.0.2 on 2026-03-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('almacenista', 'Almacenista'), ('cliente', 'Cliente')], max_length=20),
        ),
    ]
