# Generated by Copilot to include the Logistica role

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('almacenista', 'Almacenista'), ('cliente', 'Cliente'), ('logistica', 'Logística')], max_length=20),
        ),
    ]
