# Generated by Django 6.0.6 on 2026-06-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('almacenista', 'Almacenista'), ('logistica', 'Logística'), ('cliente', 'Cliente')], max_length=20),
        ),
    ]
