# Generated by Django 6.0.6 on 2026-06-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_ordenproduccion_producciondiaria_delete_produccion'),
        ('productos', '0005_producto_deleted_producto_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='producciondiaria',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='producciondiaria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.receta'),
        ),
        migrations.AlterField(
            model_name='producciondiaria',
            name='orden_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.ordenproduccion'),
        ),
    ]
