# Generated by Django 4.2.30 on 2026-07-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_ordenproduccion_deleted_ordenproduccion_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
