"""
Django settings for gafra project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h^a05x+^i-voyr2gq7^ktw##o)e--5j(s#_t@m1=84*cn)_%7p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['sash-handshake-acting.ngrok-free.dev', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuario',
    'productos',
    'proveedores',
    'produccion',
    'inventario',
    'ventas',
    'clientes',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gafra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gafra.context_processors.static_version',
                'gafra.context_processors.user_access',
            ],
        },
    },
]

WSGI_APPLICATION = 'gafra.wsgi.application'

# login redirect
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_REDIRECT_URL = '/'



# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os

# Default to a local SQLite database for development. To use MySQL set
# the environment variable GAFRA_USE_MYSQL=1 and provide the usual DB envs.
if os.environ.get('GAFRA_USE_MYSQL') in ('1', 'true', 'True'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('GAFRA_DB_NAME', 'gafra'),
            'USER': os.environ.get('GAFRA_DB_USER', 'gafra'),
            'PASSWORD': os.environ.get('GAFRA_DB_PASSWORD', ''),
            'HOST': os.environ.get('GAFRA_DB_HOST', 'localhost'),
            'PORT': os.environ.get('GAFRA_DB_PORT', '3306'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Serve project-level static files (development)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Target for collectstatic (production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Attempt to enable WhiteNoise and hashed static files when available.
import importlib
if importlib.util.find_spec('whitenoise') is not None:
    # insert WhiteNoise middleware right after SecurityMiddleware
    try:
        MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    except Exception:
        pass
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # Optional: control max-age for WhiteNoise (seconds). Keep long for hashed files.
    WHITENOISE_MAX_AGE = 31536000
else:
    # Fallback: use Django's staticfiles storage so server can run without whitenoise
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Provide a STATIC_VERSION used as fallback querystring cache-buster in templates
STATIC_VERSION = '1.0'

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
