# Generated by Django 6.0.6 on 2026-06-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_codigo_postal_proveedor_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
